### ISSUE TITLE
Only related to iPhone: Better UX for creating new threads on mobile

### ISSUE THREAD

**Issue by danieltonel** [simbacity/superapp#10]
Right now on mobile a user needs to tap twice on a message to start or open a thread. We want that the thread view opens on the first tap.

### What does success look like?

The UX for creating opening a thread should be exactly like Slack does it in it's mobile app. (one tap opens thread)

**Comment by michaelbelete** [comment]
@danieltonel inspecting `app-store\apps\town-square\components\Message.tsx` and checking the web using my mobile app and on desktop, I have found that it only takes 1 click to create or open a thread. check the code snippet below for reference 

![image](https://user-images.githubusercontent.com/50682242/204160073-a97f91a3-cf04-444d-af97-8532a6c6b525.png)

**Comment by danieltonel** [comment]
> @danieltonel inspecting `app-store\apps\town-square\components\Message.tsx` and checking the web using my mobile app and on desktop, I have found that it only takes 1 click to create or open a thread. check the code snippet below for reference
> 
> ![image](https://user-images.githubusercontent.com/50682242/204160073-a97f91a3-cf04-444d-af97-8532a6c6b525.png)

Interesting, it only happens on iPhones then. Changed the description and can take over the ticket 👍

**Comment by danieltonel** [comment]
fixed
